sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: mNk9jlOe9HMJqxIOFpUimvMNb0ZqD1Bjov9911Sxm8O6G5MbS+dOLpgYGweGJ3IH7CzQBXBVUNOaerYdWGJkJslQ5sdzYPC5extWVa5jFvH2uDSVkLdKBtmKHMPicOyuygPQzdNmYMRHP7yxOl5Dt+tml+CpACCRT79kJLUKE3/CzDszqXZ+UEMIx5EpavDHpg6IqOAX2pQGTa+IDTkkhmP1RD7b8zQ6R4eYrv4gstV4HrQxxr1P8YNZ6JoTCExppdFPE/x/glr9TERkQgbd52ui1Q9+CiC33eLvPxR+fiamC22DDa6HsWHvEi2rr8LBLBijOMWC/XvB+T3uB/EJvfRtjq62X/ZCJeHyg7m+VX+jvwcY2EubwKuas9NNy0LeLkBFTAxxxq6l4fD8tYq71Sxur/5kTS0KfdSD7FgpuqjSxOb/xVbBWTcWnWUMgvu752Syz1aCRvOwlNfaUQRs2ul8aQ/CzuZcFVArVperyyIN81HxkyCj8Fbf5s+0Q5zh/30D0QQJauhnN/W7r1PQCgWkIZ+VgW7l1jZg3q0SkaLJaGcIT2C4fRaHJDSvZTd2L/uD3RyB8Bt+uOeuZFiHq87Y1rDCsraDTo89vsjvBAsKN0zUtHYTAOM4szkWgNx6VZQdfATd+VcmBwp6AlFLNFInXnzmGpvdPPLLAMJe/bI=
    - secure: YPw9TsujrDhSlEV765Lh4CRixTxGMDYv4eNCryYPW/uI9yC5dyBo68TO+NqXjDO1S0yNIbbcZIfAadxEuJr7/Xt8Jq0Il15BhJXLxgtq9C88Kgg2qrazGF/VIds6iWjaZc9Zulss3vl3IVPPDMvcUlkEW9824FRlMQPTW8wyyUd/Oj3gMnB4Dk+IwDlw1vhWC3GNSFFe/Nl1UJTNZ42mBD1j+KA3hWBbzAoa7Imkn27c4K45whfAVAxmE/Pimr1Q/8ZYLO2pwia6qL9Ia3a0w+PyEvQLg9JPGvr/rKEDmSmhvvcSrv0/TmCGqiDFB3lf14zJ1TfEnJ8WP7COrNoy7V3GyQ0Z7BACxrOs/oLMQzJNlLlGlJf0ohja5gkgJ1ZcrIuW59ENukfGRCoWCNbNSrTEBPy084nzCr+3QJmRAXkbSGDrWRqNvXJ/o+DvVGSkHo2NgULj+cPTsh8+ieUqLZORbkvh6ue2A73Eq5Mwu5A92QrbDDrtXNjwh2L6dvHg7cnTX7e1bckyTs7auAGhJCBKEA+5dIh/jxw/g8zuTMfSnuiJszezj7cqXlhFGgLmD4I5jbGYI8iu5nGuzrYK05ieM9Q7PpFdiX7cEQWiW8qDA2aLOnp8keFSZTQ80csFbaF25OLoeqH5qDpqV6GLAUvr/+KZ94xfcp4zvXNyfqk=
